name: Unit Tests 🧪
on:
  pull_request:
    branches:
      - 'dev*'
      - 'releases/v*'
  push:
    branches:
      - 'dev*'
    tags-ignore:
      - '*.*'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install and Test
        run: |
          yarn install --frozen-lockfile
          yarn lint:check
          yarn lint:format:check
          yarn test

      - name: Uploade CodeCov Report
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build lib
        run: |
          yarn install
          yarn build

      - name: Rebuild production node_modules
        run: |
          yarn install --production --frozen-lockfile
          ls node_modules

      - name: artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: dist
          path: |
            lib
            node_modules
