name: Deploy Production Dependencies and Code 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/v*'
      - 'releases/beta'
    tags-ignore:
      - '*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Clobber lib
        run: rm -rf lib

      - name: Set up .gitignore
        run: |
          sed -i -e's/^lib/# lib/' -e's/^node_module/# node_modules/' .gitignore

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Install Production node_modules
        run: |
          yarn install --production --frozen-lockfile

      - name: Commit and Push
        # Keep the run green if the commit fails for the lack of changes
        continue-on-error: true
        env:
          GIT_CONFIG_EMAIL: ${{ secrets.GIT_CONFIG_EMAIL }}
          GIT_CONFIG_NAME: ${{ secrets.GIT_CONFIG_NAME }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          git config user.email "$GIT_CONFIG_EMAIL"
          git config user.name "$GIT_CONFIG_NAME"
          git add .
          git commit -m "Deploy Production Code for Commit $COMMIT_SHA 🚀"
          git push
